name: Deploy Django Static Files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django collectstatic
      env:
        DJANGO_SETTINGS_MODULE: jjPictures.settings
      run: |
        python manage.py collectstatic --noinput

    - name: Verify static files
      run: |
        ls -l staticfiles

    - name: Create .nojekyll file
      run: |
        touch staticfiles/.nojekyll

    - name: Check git configuration
      run: |
        git config --list
        git status

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status
        if git remote get-url origin; then
          git remote remove origin
        fi
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin
        git checkout -b gh-pages || git checkout gh-pages
        git add staticfiles
        git commit -m "Deploy static files to GitHub Pages"
        git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./staticfiles
