name: Deploy Django Static Files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django collectstatic
      env:
        DJANGO_SETTINGS_MODULE: jjPictures.settings
      run: |
        python manage.py collectstatic --noinput

    - name: Verify static files
      run: |
        echo "Listing contents of staticfiles directory..."
        ls -l staticfiles
        echo "Showing disk usage of staticfiles directory..."
        du -sh staticfiles

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status
        echo "Initializing git repository..."
        git init
        echo "Adding remote origin..."
        if git remote get-url origin; then
          git remote remove origin
        fi
        git remote add origin https://github.com/${{ github.repository }}.git
        echo "Fetching from remote origin..."
        git fetch origin
        echo "Checking out gh-pages branch..."
        if git checkout gh-pages; then
          echo "Checked out existing gh-pages branch"
        else
          echo "Creating new gh-pages branch"
          git checkout -b gh-pages
        fi
        echo "Adding staticfiles..."
        git add staticfiles
        echo "Committing changes..."
        git commit -m "Deploy static files to GitHub Pages"
        echo "Pushing to gh-pages branch..."
        git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
